apiVersion: v1
kind: Pod
metadata:
  name: bastion
  namespace: bastion
spec:
  containers:
    - image: ghcr.io/bastionmania/bastionmania/bastion:dev
      imagePullPolicy: Always
      name: bastion
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: 200m
      env:
        - name: BASTION_PRIVATE_KEY
          value: "KBuirIxRe0d8wVw/juiDE5kkCyWtDRVeQtCE+QLxn0U="
        - name: AGENT_ENDPOINT
          value: "10.10.40.10:60469"
        - name: AGENT_PUBLIC_KEY
          value: "80wp0f9G/CGkYbtMN4ZmFIknOX9mO57BVo6bK5w02Ek="
        - name: NET_CIDR
          value: "10.10.50.0/24"
        - name: NET_ID
          value: "5"
      securityContext:
        capabilities:
          add: [ "NET_ADMIN" ]
  initContainers:
    - name: init-sys
      securityContext:
        privileged: true
      image: busybox
      command: [ 'sh', '-c', 'echo 1 > /proc/sys/net/ipv4/ip_forward' ]
  imagePullSecrets:
    - name: repogithub
  restartPolicy: Always