apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: myvolume
  local:
    path: /data/volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: # List of worker nodes
          - bm-worker1
          - bm-worker2
          - bm-worker3
          - bm-worker4
          - bm-worker5
          - bm-worker6

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-nfs-claim
  namespace: bastion
spec:
  storageClassName: myvolume
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 5Gi # Sets volume size

