version: "2.1"
services:
  agent:
    image: agent
    container_name: bastion-mania-agent
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - "BM_HOST=bastionmania.intra"
      - "AGENT_HOST=10.10.40.11:60469"
      - "TOKEN=QyY="
    ports:
      - "60469:60469/udp"
    volumes:
      - ./data:/data
      - ./bastionmania.intra.pem:/certs/bastionmania.intra.pem
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped